const assets = [
  ['◒', 'Cold-water tanks', '2 tanks · 8,000 L total', 'Monthly inspection'],
  ['◉', 'Dialysis unit', 'Renal floor · 14 stations', 'Daily quality control'],
  ['▧', 'CSSD sterilisation', 'Basement level · 3 devices', 'Weekly maintenance'],
  ['≋', 'Cooling system', 'East wing · 2 towers', 'Legionella programme'],
];
const defaultRisks = [
  ['Legionella exposure', 'Cooling system · East wing', 'High', 'Temperature control and sampling', 'LM', 'Laura Martín', '18 Sep'],
  ['Stagnant water', 'Unused outlets · Ward 3', 'Medium', 'Weekly flushing programme', 'JR', 'Javier Ruiz', '14 Sep'],
  ['Water-quality interruption', 'Municipal supply', 'Medium', 'Supplier alert and contingency protocol', 'AG', 'Ana Gómez', '22 Sep'],
];
const defaultChecks = [
  {day:'10', mon:'Sep', title:'Cooling tower temperature below threshold', detail:'East wing · Sensor CT-04 · Automatic alert', state:'Overdue'},
  {day:'10', mon:'Sep', title:'Ward 3 flushing cycle not confirmed', detail:'12 outlets · Smart-valve feed · Automatic alert', state:'Overdue'},
  {day:'12', mon:'Sep', title:'Dialysis water-quality sample due', detail:'Renal floor · Laboratory feed expected', state:'Scheduled'},
  {day:'14', mon:'Sep', title:'Cold-water tank inspection due', detail:'Roof plant room · Facilities confirmation needed', state:'Scheduled'},
];
const $ = (s) => document.querySelector(s);
let actions=[{id:1,title:'Cooling tower temperature below threshold',area:'Punto de muestreo CT-04 · East wing',severity:'Critical',due:'10 Sep · 12:00',owner:'Laura Martín',initials:'LM',escalation:'Infection control notified',status:'Open',reading:'19.2 °C',threshold:'Expected operating range: 20–25 °C',consequence:'Potential Legionella growth risk affecting nearby clinical areas.',recommendation:'Isolate tower, verify sensor, take confirmatory sample, and document the acción correctiva.',history:'10 Sep 08:12 · Automatic alert created'},{id:2,title:'Ward 3 flushing cycle not confirmed',area:'Punto de muestreo · 12 unused outlets',severity:'High',due:'10 Sep · 16:00',owner:'Javier Ruiz',initials:'JR',escalation:'Facilities lead notified',status:'Open',reading:'No confirmation received',threshold:'Weekly flush confirmation required',consequence:'Stagnation may affect water quality at re-opening.',recommendation:'Complete flushing programme and attach maintenance record.',history:'10 Sep 07:30 · Reminder sent'},{id:3,title:'Dialysis water-quality sample due',area:'Punto de muestreo · Renal floor',severity:'Medium',due:'10 Sep · 18:00',owner:'Ana Gómez',initials:'AG',escalation:'Not escalated',status:'Awaiting evidence',reading:'Sample pending',threshold:'Laboratory result required before sign-off',consequence:'Dialysis service may require release hold until result is reviewed.',recommendation:'Collect sample and upload laboratory result.',history:'09 Sep 16:45 · Sampling task assigned'},{id:4,title:'Cold-water tank inspection evidence',area:'Roof plant room · Tank CW-02',severity:'Low',due:'09 Sep · 17:00',owner:'Sergio Molina',initials:'SM',escalation:'Facilities lead notified',status:'Overdue',reading:'Inspection completed; record missing',threshold:'Monthly inspection record required',consequence:'Inspection readiness gap; no immediate clinical impact identified.',recommendation:'Upload maintenance record and close the evidence gap.',history:'09 Sep 17:10 · Marked awaiting evidence'}];
const pageNames = {dashboard:'OVERVIEW',onboarding:'QUICK START',assets:'HOSPITAL SETUP',risks:'RISK REGISTER',monitoring:'MONITORING',report:'COMPLIANCE REPORT',plan:'PSA DOCUMENT'};
const hospitals = {
  santa: {name:'Santa Marina Hospital', short:'Santa Marina Hospital', initials:'SM', meta:'Madrid · 284 beds', city:'Madrid', beds:'284', user:'Laura Martín', score:'91%', readings:'26'},
  norte: {name:'Hospital del Norte', short:'Hospital del Norte', initials:'HN', meta:'Barcelona · 196 beds', city:'Barcelona', beds:'196', user:'Marc Vidal', score:'94%', readings:'31'},
  costa: {name:'Costa Salud Medical Centre', short:'Costa Salud', initials:'CS', meta:'Valencia · 118 beds', city:'Valencia', beds:'118', user:'Elena Torres', score:'88%', readings:'19'},
};
let activeHospital = localStorage.getItem('aquaguard-hospital') || 'santa';
function readData(key, fallback){try{return JSON.parse(localStorage.getItem(`aquaguard-${activeHospital}-${key}`)) ?? fallback;}catch{return fallback;}}
function saveData(key, value){localStorage.setItem(`aquaguard-${activeHospital}-${key}`, JSON.stringify(value));}
function loadHospitalData(){risks=readData('risks', defaultRisks); checks=readData('checks', defaultChecks); actions=readData('actions', actions);}
function persistAll(){saveData('risks',risks);saveData('checks',checks);saveData('actions',actions);}
function renderHospital(){
  const hospital = hospitals[activeHospital];
  $('#hospital-avatar').textContent = hospital.initials;
  $('#hospital-name').innerHTML = `${hospital.name}<small>${hospital.meta}</small>`;
  $('#welcome-hospital').textContent = hospital.short;
  $('#profile-switch').innerHTML = `${hospital.user.split(' ').map(n=>n[0]).join('')} <span>⌄</span>`;
  document.title = `AquaGuard | ${hospital.name}`;
  const setupHospital = document.querySelector('.setup-summary article strong');
  if(setupHospital) setupHospital.textContent = hospital.name;
  document.querySelectorAll('.paper-head h2').forEach(el => el.textContent = hospital.name);
  const stats = document.querySelectorAll('.stats article strong');
  stats[0].textContent = hospital.score;
  stats[3].textContent = hospital.readings;
  loadHospitalData();
  renderOnboarding();
}
let onboardingStep = 0;
function onboardingData(){ return JSON.parse(localStorage.getItem(`aquaguard-onboarding-${activeHospital}`) || '{}'); }
function saveOnboarding(data){ localStorage.setItem(`aquaguard-onboarding-${activeHospital}`, JSON.stringify(data)); }
function renderOnboarding(){
  const hospital = hospitals[activeHospital], data = onboardingData(), done = data.complete ? 4 : (data._step || 0);
  $('#onboarding-hospital-tag').textContent = hospital.name.toUpperCase();
  $('#onboarding-count').textContent = data.complete ? '✓' : `${Math.max(1, 4-done)}`;
  const labels = ['Site profile', 'Water system', 'Critical services', 'Safety team'];
  $('#onboarding-steps').innerHTML = labels.map((label,i)=>`<button class="onboarding-step ${i===onboardingStep?'active':''} ${i<done||data.complete?'done':''}" data-onboarding-step="${i}"><span>${i<done||data.complete?'✓':i+1}</span>${label}</button>`).join('');
  const panels = [
    `<p class="eyebrow">STEP 1 OF 4 · SITE PROFILE</p><h2>Tell us about ${hospital.short}.</h2><p class="lead">We use this to tailor site labels, reporting headers, and the starting compliance scope.</p><div class="onboarding-fields"><label>Hospital or clinic name<input data-onboarding="name" value="${data.name || hospital.name}" /></label><label>City<input data-onboarding="city" value="${data.city || hospital.city}" /></label><label>Number of beds / chairs<input data-onboarding="capacity" type="number" min="1" value="${data.capacity || hospital.beds}" /></label></div>`,
    `<p class="eyebrow">STEP 2 OF 4 · WATER SYSTEM</p><h2>Map the essential infrastructure.</h2><p class="lead">A simple starting map is enough. You can add detail later with your facilities team.</p><div class="onboarding-fields"><label>Primary water source<select data-onboarding="source"><option ${data.source==='Municipal supply'?'selected':''}>Municipal supply</option><option ${data.source==='Private borehole'?'selected':''}>Private borehole</option><option ${data.source==='Mixed supply'?'selected':''}>Mixed supply</option></select></label><label>Number of water-storage tanks<input data-onboarding="tanks" type="number" min="0" value="${data.tanks ?? 0}" /></label><label>Buildings or clinical areas<input data-onboarding="areas" value="${data.areas || 'Main building'}" /></label></div>`,
    `<p class="eyebrow">STEP 3 OF 4 · CRITICAL SERVICES</p><h2>Identify priority water uses.</h2><p class="lead">We will suggest relevant monitoring points and controls for the services you select.</p><div class="service-options">${['Dialysis','ICU / critical care','Sterilisation (CSSD)','Dental care','Cooling towers'].map(service=>`<label><input data-service="${service}" type="checkbox" ${(data.services || []).includes(service)?'checked':''} />${service}</label>`).join('')}</div>`,
    `<p class="eyebrow">STEP 4 OF 4 · SAFETY TEAM</p><h2>Choose the accountable lead.</h2><p class="lead">Invite the rest of the team later. This person receives the first monitoring and review reminders.</p><div class="onboarding-fields"><label>Water-safety lead<input data-onboarding="lead" value="${data.lead || hospital.user}" /></label><label>Lead email<input data-onboarding="leadEmail" type="email" value="${data.leadEmail || ''}" placeholder="name@hospital.org" /></label></div>`
  ];
  $('#onboarding-content').innerHTML = `<div class="onboarding-panel">${panels[onboardingStep]}<div class="dialog-actions"><button class="secondary" id="onboarding-back" ${onboardingStep===0?'disabled':''}>Back</button><button class="primary" id="onboarding-next">${onboardingStep===3?'Finish setup':'Continue'} <span>→</span></button></div></div>`;
  const source = data.source || 'Municipal supply', areas = data.areas || 'Main building', tanks = Number(data.tanks || 0), services = data.services?.length ? data.services : ['Critical clinical units'];
  const tankLabel = tanks ? `${tanks} storage tank${tanks === 1 ? '' : 's'}` : 'Direct distribution';
  $('#map-status').textContent = data.complete ? 'BASELINE READY' : 'DRAFT MAP';
  $('#onboarding-map').innerHTML = `<div class="map-node source"><span>◉</span><strong>${source}</strong><small>Water source</small></div><div class="map-connector"><i>→</i></div><div class="map-node site"><span>⌂</span><strong>${areas}</strong><small>${data.capacity || hospital.beds} beds / chairs</small></div><div class="map-branch"><div class="map-connector"><i>↓</i></div><div class="map-node storage"><span>▣</span><strong>${tankLabel}</strong><small>Storage & distribution</small></div><div class="map-connector"><i>→</i></div><div class="map-node critical"><span>✚</span><strong>${services.join(' · ')}</strong><small>Critical units</small></div></div>`;
  document.querySelectorAll('[data-onboarding-step]').forEach(button=>button.onclick=()=>{onboardingStep=Number(button.dataset.onboardingStep);renderOnboarding();});
  $('#onboarding-back').onclick=()=>{if(onboardingStep){onboardingStep--;renderOnboarding();}};
  $('#onboarding-next').onclick=()=>{
    const next = onboardingData();
    document.querySelectorAll('[data-onboarding]').forEach(input=>next[input.dataset.onboarding]=input.value);
    if(onboardingStep===2) next.services=[...document.querySelectorAll('[data-service]:checked')].map(input=>input.dataset.service);
    next._step = Math.max(next._step || 0, onboardingStep + 1);
    if(onboardingStep===3){ next.complete=true; saveOnboarding(next); renderOnboarding(); toast(`${hospital.name} is ready for monitoring.`); showPage('dashboard'); return; }
    saveOnboarding(next); onboardingStep++; renderOnboarding();
  };
}
function openLogin(){
  $('#hospital-select').innerHTML = Object.entries(hospitals).map(([id,h])=>`<option value="${id}" ${id===activeHospital?'selected':''}>${h.name} — ${h.meta}</option>`).join('');
  $('#login-email').value = '';
  $('#login-password').value = '';
  $('#hospital-login').showModal();
  $('#login-email').focus();
}
$('#hospital-switcher').onclick = openLogin;
$('#profile-switch').onclick = openLogin;
$('#login-form').addEventListener('submit', event => {
  if(!$('#login-email').checkValidity() || !$('#login-password').checkValidity()) { event.preventDefault(); return; }
  activeHospital = $('#hospital-select').value;
  localStorage.setItem('aquaguard-hospital', activeHospital);
  renderHospital();
  toast(`Connected to ${hospitals[activeHospital].name}.`);
});
function badge(level){ return `<span class="badge ${level === 'High' || level === 'Overdue' ? 'high' : level === 'Medium' ? 'medium' : 'low'}">${level}</span>`; }
function renderAssets(){ $('#asset-grid').innerHTML = assets.map(a=>`<article class="asset"><span>${a[0]}</span><h3>${a[1]}</h3><p>${a[2]}</p><small>${a[3]}</small></article>`).join(''); }
function renderRisks(){ $('#risk-table').innerHTML = risks.map(r=>`<tr><td><strong>${r[0]}</strong><small>${r[1]}</small></td><td>${badge(r[2])}</td><td>${r[3]}</td><td><div class="owner"><span class="avatar">${r[4]}</span>${r[5]}</div></td><td>${r[6]}</td></tr>`).join(''); $('#risk-count').textContent = risks.filter(r=>r[2] !== 'Low').length; }
function renderChecks(){ $('#monitoring-list').innerHTML = checks.map((c,i)=>`<div class="monitoring-row"><div class="date-pill"><strong>${c.day}</strong><span>${c.mon}</span></div><div><h3>${c.title}</h3><p>${c.detail}</p></div>${badge(c.state)}${c.state==='Overdue'?`<button class="check-button" data-check="${i}">Complete</button>`:''}</div>`).join(''); const overdue=checks.filter(c=>c.state==='Overdue'); $('#overdue-total').textContent=overdue.length; $('#monitor-count').textContent=overdue.length; $('#attention-list').innerHTML=overdue.map(c=>`<div class="attention-item"><span class="attention-symbol amber">!</span><div><strong>${c.title}</strong><small>${c.detail}</small></div><button data-page-target="monitoring">Complete →</button></div>`).join('') || '<p class="lead">Everything is up to date. Nice work.</p>'; document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{checks[Number(b.dataset.check)].state='Complete'; persistAll(); renderChecks(); toast('Check recorded in the audit trail.');}); }
function showPage(id){ document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id)); document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===id)); $('#page-name').textContent=pageNames[id]; window.scrollTo({top:0,behavior:'smooth'}); }
document.querySelectorAll('[data-page], [data-page-target]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page || b.dataset.pageTarget)));
let entryType=''; const dialog=$('#entry-dialog');
function openDialog(type){entryType=type; $('#dialog-kicker').textContent=type.toUpperCase(); $('#dialog-title').textContent=type==='risk'?'Add a risk':'Add a reading'; $('#record-title').placeholder=type==='risk'?'e.g. Legionella exposure':'e.g. Tank temperature reading'; $('#record-detail').placeholder=type==='risk'?'e.g. East-wing cooling tower':'e.g. Sensor CT-04'; dialog.showModal();}
$('#add-risk').onclick=()=>openDialog('risk'); $('#add-check').onclick=()=>openDialog('check'); $('#add-asset').onclick=()=>toast('Asset creation is available in the full workflow.');
$('#save-record').onclick=()=>{ if(!$('#record-title').checkValidity()||!$('#record-detail').checkValidity()) return; const title=$('#record-title').value.trim(), detail=$('#record-detail').value.trim(); if(entryType==='risk'){risks.push([title,detail,'Medium','Control measure to be defined','SM','Safety Manager','Review due']); renderRisks();} else {checks.unshift({day:'10',mon:'Sep',title,detail,state:'Scheduled'});renderChecks();} persistAll(); $('#entry-dialog').close(); $('#record-title').value='';$('#record-detail').value='';toast('Record saved successfully.');};
$('#export-plan').onclick=()=>toast('Your PSA export is being prepared.');
$('#export-report').onclick=()=>{const open=actions.filter(a=>a.status!=='Resolved'),complete=checks.filter(c=>c.state==='Complete').length;const text=`AquaGuard compliance report\n${hospitals[activeHospital].name}\nGenerated: ${new Date().toLocaleString()}\n\nMonitoring checks complete: ${complete}/${checks.length}\nOpen corrective actions: ${open.length}\n\nOpen actions:\n${open.map(a=>`- ${a.title} (${a.severity}) — ${a.owner}`).join('\n')||'- None'}`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'})),link=document.createElement('a');link.href=url;link.download=`aquaguard-${activeHospital}-compliance-report.txt`;link.click();URL.revokeObjectURL(url);};
function toast(message){const el=$('#toast');el.textContent=message;el.className='show';setTimeout(()=>el.className='',2800);}
function renderActions(){const open=actions.filter(a=>a.status!=='Resolved');$('#action-summary').innerHTML=`<button><strong>${open.filter(a=>a.severity==='Critical').length}</strong><span>critical actions</span></button><button><strong>${open.filter(a=>a.due.includes('10 Sep')).length}</strong><span>due today</span></button><button><strong>${open.filter(a=>a.status==='Overdue').length}</strong><span>overdue</span></button><button><strong>${open.filter(a=>a.status==='Awaiting evidence').length}</strong><span>awaiting evidence</span></button>`;$('#attention-list').innerHTML=open.map(a=>`<article class="action-row ${a.severity.toLowerCase()}"><div class="action-priority">${a.severity[0]}</div><div class="action-main"><strong>${a.title}</strong><small>${a.area}</small><div class="action-meta">${badge(a.severity)} <span>Due ${a.due}</span><span class="owner"><span class="avatar">${a.initials}</span>${a.owner}</span></div></div><div class="action-state"><span>${a.status}</span><small>${a.escalation}</small></div><button class="text-button open-action" data-action="${a.id}">Open →</button></article>`).join('');document.querySelectorAll('.open-action').forEach(b=>b.onclick=()=>openAction(+b.dataset.action));}
let selectedAction;function openAction(id){selectedAction=actions.find(a=>a.id===id);$('#action-title').textContent=selectedAction.title;$('#action-detail').innerHTML=`<div class="detail-grid"><p><b>Área / punto de muestreo</b>${selectedAction.area}</p><p><b>Lectura / observación</b>${selectedAction.reading}<br>${selectedAction.threshold}</p><p><b>Fecha y hora</b>10 Sep 2026 · 08:12 CET</p><p><b>Consecuencia operativa</b>${selectedAction.consequence}</p><p><b>Acción correctiva recomendada</b>${selectedAction.recommendation}</p><p><b>Persona responsable · deadline</b>${selectedAction.owner} · ${selectedAction.due}</p><p><b>Escalación</b>${selectedAction.escalation}</p><p><b>Historial de actividad</b>${selectedAction.history}</p></div>`;$('#action-dialog').showModal();}$('#resolve-action').onclick=()=>{$('#action-dialog').close();$('#resolve-dialog').showModal()};$('#save-resolution').onclick=()=>{if(!$('#resolution-notes').checkValidity()||!$('#resolution-owner').checkValidity())return;selectedAction.status='Resolved';selectedAction.history+=` · Resuelto por ${$('#resolution-owner').value}, 10 Sep 2026 · 09:05 CET`;selectedAction.evidence=$('#evidence-file').files[0]?.name||'Nota de acción registrada';saveData('actions',actions);$('#resolve-dialog').close();renderActions();toast('Action resolved and preserved in the audit trail.');};
const nl=String.fromCharCode(10);const pdfText=s=>{let out='';for(const ch of String(s)){const c=ch.charCodeAt(0);out+=c>=32&&c<=126?ch:'?';}return out.replaceAll('\\','\\\\').replaceAll('(','\\(').replaceAll(')','\\)');};function makePdf(lines){const stream=['BT','/F1 14 Tf','50 770 Td',...lines.flatMap((x,i)=>[i?'0 -22 Td':'',`(${pdfText(x)}) Tj`]),'ET'].join(nl),enc=new TextEncoder(),objects=[`<< /Type /Catalog /Pages 2 0 R >>`,`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`,`<< /Length ${enc.encode(stream).length} >>${nl}stream${nl}${stream}${nl}endstream`];let pdf='%PDF-1.4'+nl,offsets=[];objects.forEach((o,i)=>{offsets[i]=enc.encode(pdf).length;pdf+=`${i+1} 0 obj${nl}${o}${nl}endobj${nl}`;});const x=enc.encode(pdf).length;pdf+=`xref${nl}0 6${nl}0000000000 65535 f ${nl}${offsets.map(o=>String(o).padStart(10,'0')+' 00000 n '+nl).join('')}trailer${nl}<< /Size 6 /Root 1 0 R >>${nl}startxref${nl}${x}${nl}%%EOF`;return new Blob([enc.encode(pdf)],{type:'application/pdf'});}
$('#export-report').onclick=()=>{const open=actions.filter(a=>a.status!=='Resolved'),complete=checks.filter(c=>c.state==='Complete').length,lines=['AquaGuard compliance report',hospitals[activeHospital].name,`Generated: ${new Date().toLocaleString()}`,'',`Monitoring checks complete: ${complete}/${checks.length}`,`Open corrective actions: ${open.length}`,'','Open actions:',...open.map(a=>`- ${a.title} (${a.severity}) - ${a.owner}`)],url=URL.createObjectURL(makePdf(lines)),link=document.createElement('a');link.href=url;link.download=`aquaguard-${activeHospital}-compliance-report.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const publicDataCard=document.createElement('section');publicDataCard.className='card public-data-card';publicDataCard.innerHTML='<p class="eyebrow">PUBLIC DATA · EUROSTAT</p><h2>European water-use context</h2><p class="lead">Live public data adds context to the hospital demo.</p><strong id="eurostat-value">Loading…</strong><p id="eurostat-label">Fetching Spain water data</p><small>Source: Eurostat API · env_wat_abs · Spain</small>';document.querySelector('.context-grid').after(publicDataCard);async function loadEurostatWaterData(){try{const r=await fetch('https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/env_wat_abs?geo=ES&lang=en'),d=await r.json(),v=Object.values(d.value||{}).filter(Number.isFinite);$('#eurostat-value').textContent=v.length?new Intl.NumberFormat('en-GB').format(v[v.length-1]):'Unavailable';$('#eurostat-label').textContent=v.length?'Latest reported water-abstraction value':'Eurostat unavailable';}catch{$('#eurostat-value').textContent='Unavailable';$('#eurostat-label').textContent='Eurostat unavailable';}}
function makeLayoutPdf(rows){const cmds=['q','0.94 0.98 0.98 rg','0 0 612 792 re','f','Q','0.06 0.25 0.28 rg','40 700 532 52 re','f'];const text=(s,x,y,size=10,color='0.08 0.18 0.2')=>{cmds.push(`${color} rg`,`BT /F1 ${size} Tf ${x} ${y} Td (${pdfText(s)}) Tj ET`);};const box=(x,y,w,h)=>{cmds.push('0.82 0.9 0.89 RG',`${x} ${y} ${w} ${h} re`,`S`);};text('AquaGuard',58,724,22,'1 1 1');text('WATER-QUALITY COMPLIANCE REPORT',58,708,9,'0.75 0.95 0.92');text(rows.hospital,58,674,18,'0.06 0.25 0.28');text(`Generated ${rows.generated}`,58,658,9);box(40,570,165,58);box(223,570,165,58);box(406,570,166,58);text('COMPLIANCE SCORE',54,610,8,'0.2 0.4 0.42');text('91%',54,585,22,'0.06 0.45 0.48');text('CHECKS COMPLETE',237,610,8,'0.2 0.4 0.42');text(`${rows.complete}/${rows.total}`,237,585,22,'0.06 0.45 0.48');text('OPEN ACTIONS',420,610,8,'0.2 0.4 0.42');text(String(rows.open.length),420,585,22,rows.open.length?'0.75 0.3 0.18':'0.06 0.45 0.48');text('ACTION REGISTER',40,540,13,'0.06 0.25 0.28');let y=515;rows.open.slice(0,7).forEach((a,i)=>{box(40,y-30,532,42);text(a.severity.toUpperCase(),52,y-5,8,a.severity==='Critical'?'0.75 0.2 0.12':'0.55 0.35 0.08');text(a.title,130,y-5,10);text(`${a.area} | Owner: ${a.owner} | Due: ${a.due}`,130,y-20,8,'0.3 0.4 0.42');y-=52;});if(!rows.open.length)text('No open corrective actions.',52,y-5,10);text('MONITORING EVIDENCE',40,135,13,'0.06 0.25 0.28');text(`${rows.complete} of ${rows.total} monitoring checks complete. Remaining exceptions are listed above.`,40,116,9);text('DATA NOTE',40,82,9,'0.2 0.4 0.42');text('Hospital records shown in this prototype are illustrative demo data.',40,64,8);text('Public context: Eurostat API dataset env_wat_abs, Spain.',40,50,8);const stream=cmds.join(nl),enc=new TextEncoder(),objects=[`<< /Type /Catalog /Pages 2 0 R >>`,`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`,`<< /Length ${enc.encode(stream).length} >>${nl}stream${nl}${stream}${nl}endstream`];let pdf='%PDF-1.4'+nl,offsets=[];objects.forEach((o,i)=>{offsets[i]=enc.encode(pdf).length;pdf+=`${i+1} 0 obj${nl}${o}${nl}endobj${nl}`;});const x=enc.encode(pdf).length;pdf+=`xref${nl}0 6${nl}0000000000 65535 f ${nl}${offsets.map(o=>String(o).padStart(10,'0')+' 00000 n '+nl).join('')}trailer${nl}<< /Size 6 /Root 1 0 R >>${nl}startxref${nl}${x}${nl}%%EOF`;return new Blob([enc.encode(pdf)],{type:'application/pdf'});}
$('#export-report').onclick=()=>{const open=actions.filter(a=>a.status!=='Resolved'),complete=checks.filter(c=>c.state==='Complete').length;const url=URL.createObjectURL(makeLayoutPdf({hospital:hospitals[activeHospital].name,generated:new Date().toLocaleString(),complete,total:checks.length,open})),link=document.createElement('a');link.href=url;link.download=`aquaguard-${activeHospital}-compliance-report.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#export-plan').onclick=()=>{const open=actions.filter(a=>a.status!=='Resolved'),complete=checks.filter(c=>c.state==='Complete').length;const url=URL.createObjectURL(makeLayoutPdf({hospital:hospitals[activeHospital].name,generated:new Date().toLocaleString(),complete,total:checks.length,open})),link=document.createElement('a');link.href=url;link.download=`aquaguard-${activeHospital}-psa-document.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function makePsaPdf(hospital){const cmds=['q','0.94 0.98 0.98 rg','0 0 612 792 re','f','Q','0.06 0.25 0.28 rg','40 700 532 52 re','f'];const text=(s,x,y,size=10,color='0.08 0.18 0.2')=>cmds.push(`${color} rg`,`BT /F1 ${size} Tf ${x} ${y} Td (${pdfText(s)}) Tj ET`);const section=(n,title,body,y)=>{cmds.push('0.82 0.9 0.89 RG',`40 ${y-22} 532 46 re`,'S');text(n,54,y,12,'0.06 0.45 0.48');text(title,92,y+2,11);text(body,92,y-14,8,'0.3 0.4 0.42');};text('AquaGuard',58,724,22,'1 1 1');text('PLAN SANITARIO DEL AGUA',58,708,9,'0.75 0.95 0.92');text(hospital,58,674,18,'0.06 0.25 0.28');text('Version 1.4 | Draft for annual review',58,658,9);text('PLAN CONTENT',40,620,13,'0.06 0.25 0.28');section('01','Building and water-system description','Municipal supply, two cold-water storage tanks, twelve distribution zones, and critical clinical units mapped.',590);section('02','Risk assessment and control measures','14 hazards assessed, including Legionella exposure, stagnation, and supply interruption. Three items scheduled for review.',530);section('03','Monitoring and corrective actions','Connected readings, laboratory evidence, owners, deadlines, and corrective-action records are maintained in the workspace.',470);section('04','Annual verification and approval','Management sign-off is pending. Target approval date: 15 December 2026.',410);text('CURRENT STATUS',40,340,13,'0.06 0.25 0.28');cmds.push('0.82 0.9 0.89 RG','40 275 532 48 re','S');text('Ready with actions',54,302,14,'0.75 0.3 0.18');text('Resolve monitoring exceptions before final approval.',54,284,9);text('DOCUMENT CONTROL',40,235,10,'0.2 0.4 0.42');text('Prepared for the hospital water-safety team.',40,216,9);text('Illustrative prototype data; verify official requirements before production use.',40,198,8);const stream=cmds.join(nl),enc=new TextEncoder(),objects=[`<< /Type /Catalog /Pages 2 0 R >>`,`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`,`<< /Length ${enc.encode(stream).length} >>${nl}stream${nl}${stream}${nl}endstream`];let pdf='%PDF-1.4'+nl,offsets=[];objects.forEach((o,i)=>{offsets[i]=enc.encode(pdf).length;pdf+=`${i+1} 0 obj${nl}${o}${nl}endobj${nl}`;});const x=enc.encode(pdf).length;pdf+=`xref${nl}0 6${nl}0000000000 65535 f ${nl}${offsets.map(o=>String(o).padStart(10,'0')+' 00000 n '+nl).join('')}trailer${nl}<< /Size 6 /Root 1 0 R >>${nl}startxref${nl}${x}${nl}%%EOF`;return new Blob([enc.encode(pdf)],{type:'application/pdf'});}
$('#export-plan').onclick=()=>{const url=URL.createObjectURL(makePsaPdf(hospitals[activeHospital].name)),link=document.createElement('a');link.href=url;link.download=`aquaguard-${activeHospital}-psa-document.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
renderHospital();renderAssets();renderRisks();renderChecks();renderActions();loadEurostatWaterData();
