const assets = [
  ['◒', 'Cold-water tanks', '2 tanks · 8,000 L total', 'Monthly inspection'],
  ['◉', 'Dialysis unit', 'Renal floor · 14 stations', 'Daily quality control'],
  ['▧', 'CSSD sterilisation', 'Basement level · 3 devices', 'Weekly maintenance'],
  ['≋', 'Cooling system', 'East wing · 2 towers', 'Legionella programme'],
];
let risks = [
  ['Legionella exposure', 'Cooling system · East wing', 'High', 'Temperature control and sampling', 'LM', 'Laura Martín', '18 Sep'],
  ['Stagnant water', 'Unused outlets · Ward 3', 'Medium', 'Weekly flushing programme', 'JR', 'Javier Ruiz', '14 Sep'],
  ['Water-quality interruption', 'Municipal supply', 'Medium', 'Supplier alert and contingency protocol', 'AG', 'Ana Gómez', '22 Sep'],
];
let checks = [
  {day:'10', mon:'Sep', title:'Cooling tower temperature below threshold', detail:'East wing · Sensor CT-04 · Automatic alert', state:'Overdue'},
  {day:'10', mon:'Sep', title:'Ward 3 flushing cycle not confirmed', detail:'12 outlets · Smart-valve feed · Automatic alert', state:'Overdue'},
  {day:'12', mon:'Sep', title:'Dialysis water-quality sample due', detail:'Renal floor · Laboratory feed expected', state:'Scheduled'},
  {day:'14', mon:'Sep', title:'Cold-water tank inspection due', detail:'Roof plant room · Facilities confirmation needed', state:'Scheduled'},
];
const $ = (s) => document.querySelector(s);
let actions=[{id:1,title:'Cooling tower temperature below threshold',area:'Punto de muestreo CT-04 · East wing',severity:'Critical',due:'10 Sep · 12:00',owner:'Laura Martín',initials:'LM',escalation:'Infection control notified',status:'Open',reading:'19.2 °C',threshold:'Expected operating range: 20–25 °C',consequence:'Potential Legionella growth risk affecting nearby clinical areas.',recommendation:'Isolate tower, verify sensor, take confirmatory sample, and document the acción correctiva.',history:'10 Sep 08:12 · Automatic alert created'},{id:2,title:'Ward 3 flushing cycle not confirmed',area:'Punto de muestreo · 12 unused outlets',severity:'High',due:'10 Sep · 16:00',owner:'Javier Ruiz',initials:'JR',escalation:'Facilities lead notified',status:'Open',reading:'No confirmation received',threshold:'Weekly flush confirmation required',consequence:'Stagnation may affect water quality at re-opening.',recommendation:'Complete flushing programme and attach maintenance record.',history:'10 Sep 07:30 · Reminder sent'},{id:3,title:'Dialysis water-quality sample due',area:'Punto de muestreo · Renal floor',severity:'Medium',due:'10 Sep · 18:00',owner:'Ana Gómez',initials:'AG',escalation:'Not escalated',status:'Awaiting evidence',reading:'Sample pending',threshold:'Laboratory result required before sign-off',consequence:'Dialysis service may require release hold until result is reviewed.',recommendation:'Collect sample and upload laboratory result.',history:'09 Sep 16:45 · Sampling task assigned'},{id:4,title:'Cold-water tank inspection evidence',area:'Roof plant room · Tank CW-02',severity:'Low',due:'09 Sep · 17:00',owner:'Sergio Molina',initials:'SM',escalation:'Facilities lead notified',status:'Overdue',reading:'Inspection completed; record missing',threshold:'Monthly inspection record required',consequence:'Inspection readiness gap; no immediate clinical impact identified.',recommendation:'Upload maintenance record and close the evidence gap.',history:'09 Sep 17:10 · Marked awaiting evidence'}];
const pageNames = {dashboard:'OVERVIEW',assets:'HOSPITAL SETUP',risks:'RISK REGISTER',monitoring:'MONITORING',report:'COMPLIANCE REPORT',plan:'PSA DOCUMENT'};
function badge(level){ return `<span class="badge ${level === 'High' || level === 'Overdue' ? 'high' : level === 'Medium' ? 'medium' : 'low'}">${level}</span>`; }
function renderAssets(){ $('#asset-grid').innerHTML = assets.map(a=>`<article class="asset"><span>${a[0]}</span><h3>${a[1]}</h3><p>${a[2]}</p><small>${a[3]}</small></article>`).join(''); }
function renderRisks(){ $('#risk-table').innerHTML = risks.map(r=>`<tr><td><strong>${r[0]}</strong><small>${r[1]}</small></td><td>${badge(r[2])}</td><td>${r[3]}</td><td><div class="owner"><span class="avatar">${r[4]}</span>${r[5]}</div></td><td>${r[6]}</td></tr>`).join(''); $('#risk-count').textContent = risks.filter(r=>r[2] !== 'Low').length; }
function renderChecks(){ $('#monitoring-list').innerHTML = checks.map((c,i)=>`<div class="monitoring-row"><div class="date-pill"><strong>${c.day}</strong><span>${c.mon}</span></div><div><h3>${c.title}</h3><p>${c.detail}</p></div>${badge(c.state)}${c.state==='Overdue'?`<button class="check-button" data-check="${i}">Complete</button>`:''}</div>`).join(''); const overdue=checks.filter(c=>c.state==='Overdue'); $('#overdue-total').textContent=overdue.length; $('#monitor-count').textContent=overdue.length; $('#attention-list').innerHTML=overdue.map((c,i)=>`<div class="attention-item"><span class="attention-symbol amber">!</span><div><strong>${c.title}</strong><small>${c.detail}</small></div><button data-page-target="monitoring">Complete →</button></div>`).join('') || '<p class="lead">Everything is up to date. Nice work.</p>'; document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{checks[Number(b.dataset.check)].state='Complete'; renderChecks(); toast('Check recorded in the audit trail.');}); }
function showPage(id){ document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id)); document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===id)); $('#page-name').textContent=pageNames[id]; window.scrollTo({top:0,behavior:'smooth'}); }
document.querySelectorAll('[data-page], [data-page-target]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page || b.dataset.pageTarget)));
let entryType=''; const dialog=$('#entry-dialog');
function openDialog(type){entryType=type; $('#dialog-kicker').textContent=type.toUpperCase(); $('#dialog-title').textContent=type==='risk'?'Add a risk':'Add a reading'; $('#record-title').placeholder=type==='risk'?'e.g. Legionella exposure':'e.g. Tank temperature reading'; $('#record-detail').placeholder=type==='risk'?'e.g. East-wing cooling tower':'e.g. Sensor CT-04'; dialog.showModal();}
$('#add-risk').onclick=()=>openDialog('risk'); $('#add-check').onclick=()=>openDialog('check'); $('#add-asset').onclick=()=>toast('Asset creation is available in the full workflow.');
$('#save-record').onclick=(e)=>{ if(!$('#record-title').checkValidity()||!$('#record-detail').checkValidity()) return; const title=$('#record-title').value, detail=$('#record-detail').value; if(entryType==='risk'){risks.push([title,detail,'Medium','Control measure to be defined','SM','Safety Manager','Review due']); renderRisks();} else {checks.unshift({day:'10',mon:'Sep',title,detail,state:'Scheduled'});renderChecks();} $('#record-title').value='';$('#record-detail').value='';toast('Record saved successfully.');};
$('#export-plan').onclick=()=>toast('Your PSA export is being prepared.');
$('#export-report').onclick=()=>toast('Your compliance report export is being prepared.');
function toast(message){const el=$('#toast');el.textContent=message;el.className='show';setTimeout(()=>el.className='',2800);}
function renderActions(){const open=actions.filter(a=>a.status!=='Resolved');$('#action-summary').innerHTML=`<button><strong>${open.filter(a=>a.severity==='Critical').length}</strong><span>critical actions</span></button><button><strong>${open.filter(a=>a.due.includes('10 Sep')).length}</strong><span>due today</span></button><button><strong>${open.filter(a=>a.status==='Overdue').length}</strong><span>overdue</span></button><button><strong>${open.filter(a=>a.status==='Awaiting evidence').length}</strong><span>awaiting evidence</span></button>`;$('#attention-list').innerHTML=open.map(a=>`<article class="action-row ${a.severity.toLowerCase()}"><div class="action-priority">${a.severity[0]}</div><div class="action-main"><strong>${a.title}</strong><small>${a.area}</small><div class="action-meta">${badge(a.severity)} <span>Due ${a.due}</span><span class="owner"><span class="avatar">${a.initials}</span>${a.owner}</span></div></div><div class="action-state"><span>${a.status}</span><small>${a.escalation}</small></div><button class="text-button open-action" data-action="${a.id}">Open →</button></article>`).join('');document.querySelectorAll('.open-action').forEach(b=>b.onclick=()=>openAction(+b.dataset.action));}
let selectedAction;function openAction(id){selectedAction=actions.find(a=>a.id===id);$('#action-title').textContent=selectedAction.title;$('#action-detail').innerHTML=`<div class="detail-grid"><p><b>Área / punto de muestreo</b>${selectedAction.area}</p><p><b>Lectura / observación</b>${selectedAction.reading}<br>${selectedAction.threshold}</p><p><b>Fecha y hora</b>10 Sep 2026 · 08:12 CET</p><p><b>Consecuencia operativa</b>${selectedAction.consequence}</p><p><b>Acción correctiva recomendada</b>${selectedAction.recommendation}</p><p><b>Persona responsable · deadline</b>${selectedAction.owner} · ${selectedAction.due}</p><p><b>Escalación</b>${selectedAction.escalation}</p><p><b>Historial de actividad</b>${selectedAction.history}</p></div>`;$('#action-dialog').showModal();}$('#resolve-action').onclick=()=>{$('#action-dialog').close();$('#resolve-dialog').showModal()};$('#save-resolution').onclick=()=>{if(!$('#resolution-notes').checkValidity()||!$('#resolution-owner').checkValidity())return;selectedAction.status='Resolved';selectedAction.history+=` · Resuelto por ${$('#resolution-owner').value}, 10 Sep 2026 · 09:05 CET`;selectedAction.evidence=$('#evidence-file').files[0]?.name||'Nota de acción registrada';$('#resolve-dialog').close();renderActions();toast('Action resolved and preserved in the audit trail.');};
renderAssets();renderRisks();renderChecks();renderActions();
